config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://gumides.rubyonrails.org/routing.html

  root to: "pages#home"
  get "filosofie", to: "pages#filosofie"
  get "literatuur", to: "pages#literatuur"

  scope(path_names: { new: "new" }) do
    resources :news_items, path: "nieuws"
  end

  get "login", to: "sessions#new"
  get "admin", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 1, maximum: 50 }
  validates :body, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :news_items 

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  
  before_save { self.email = email.downcase }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :logged_in?, :current_user

def current_user
  return @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
  return !!current_user
end

def require_user
  if not logged_in?
    redirect_to root_path
  end
end

end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  
  before_action :set_news_item, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except:[:show, :index]
  before_action :require_same_user, only:[:edit, :update, :destroy]

  def index
    @news_items = NewsItem.all.order("created_at ASC")
  end
  
  def new 
    @news_item = NewsItem.new
  end

  def create
    @news_item = NewsItem.new(news_item_params)
    @news_item.user = current_user

    if @news_item.save
      flash[:notice] = "The news item was sucessfully created."
      redirect_to news_item_path(@news_item)
    else 
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @news_item.update(news_item_params)
      flash[:notice] = "The news item was sucessfully updated."
      redirect_to news_item_path(@news_item)
    else 
      render :edit
    end
  end

  def destroy
    if @news_item.destroy
      flash[:notice] = "News item was sucessfully deleted."
      redirect_to news_items_path()
    else
      flash[:notice] = "News item could not be deleted."
      redirect_to news_items_path()
    end
  end

private
  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end
  
  def news_item_params
    params.require(:news_item).permit(:title, :body, :show)
  end

  def require_same_user
    if current_user.admin
      return true
    end
    if current_user != @news_item.user
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  
  end

  def filosofie

  end

  def literatuur

  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.username}!"
      redirect_to root_path
    else 
      flash.now[:danger] = "Invalid email & password combination."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#333333">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#8fbc8f">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.haml
!!!
%html(lang="nl")
  %head
    %title 
      Leen Verheyen
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    / Required meta tags
    %meta{charset: "utf-8"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}

  %body
    .container-md
      = render "shared/header"
      
      - flash.each do |name, msg|
        .row
          .flash-message.note.col-sm-8.offset-sm-2.col-md-6.offset-md-3.col-lg-4.offset-lg-4
            %h6.center
              = msg

      %main
        = yield

      = render "shared/footer"  

app/views/news_items/_form_news_item.html.haml
.note
  %h2.center 
    Aanmaken nieuw nieuwsitem
  .col
    = render "shared/flash_messages", obj: @news_item
  = form_for @news_item do |f|
    .row
      .col 
        = f.label :title, "Titel"
      .col  
        = f.text_field :title, { :placeholder => "verplicht" }
    .row
      .col 
        = f.label :body, "Bericht"
      .col
        = f.text_area :body, { :placeholder => "verplicht" }
    .row 
      .col
        = f.label :show, "Bericht publiceren"
        = f.check_box :show, { :value => "published", :checked => true }
      .col
        %button 
          = f.submit @news_item.new_record? ? "Bericht aanmaken" : "Bericht bijwerken"

app/views/news_items/edit.html.haml
%h2 
  Nieuwsbericht bewerken 

= render partial: "form_news_item"

app/views/news_items/index.html.haml
.row
- @news_items.each do |news_item|  
  - if news_item.show
    .col-xs-6
      %article.note
        %h3
          = news_item.title
        - if logged_in? && current_user.admin
          .admin-actions
            = link_to "", edit_news_item_path(news_item), class: "icon icon-pen"
            %span 
              &emsp;|&emsp; 
            %span.delete 
              = link_to "", news_item_path(news_item), method: :delete, data: { confirm: "Are you certain you want to delete this news item?" }, class: "icon icon-bin" 
        %p  
          = news_item.body
        %p 
          %small
            Van:
            = news_item.user.username if news_item.user
            Gemaakt op 
            = news_item.created_at.strftime("%d/%m/%Y").to_s

app/views/news_items/new.html.haml
= render partial: "form_news_item"

app/views/news_items/show.html.haml
%h1
  = @news_item.title
%p 
  = @news_item.body

app/views/pages/filosofie.html.haml
.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3
      Doctoraatsonderzoek
    %p
      Momenteel ben ik als Aspirant van het FWO (Fonds Wetenschappelijk Onderzoek – Vlaanderen) verbonden aan het Centrum voor Europese Filosofie van de Universiteit Antwerpen. Daar werk ik aan een doctoraatsonderzoek met als titel&nbsp;
      %strong> Literature, Truth and Meaning
      ! . Concreet probeer ik in mijn onderzoek een antwoord te formuleren op de vraag wat de cognitieve waarde van literaire fictie is. In 2018 mocht ik hierover kort iets vertellen in het één programma&nbsp;
      %em> Iedereen Beroemd
      ! . 
      .vid
        .youtube{ :data => { :embed => 'iAo3I0TDU5A' } }
          .play-button"> 
      %p  
        In datzelfde jaar schreef ik ook een stukje voor de filosofische blog 
        %a{ :target => "_blank", :href => "https://bijnaderinzien.org/2018/02/12/leidt-literatuur-tot-kennis/" } Bij nader inzien
        waarin ik mijn insteek in het hedendaagse debat uiteen zet. Daarnaast verscheen er ook een wetenschappelijk artikel over 
        %strong{ :style => "font-weight:normal" } Paul Ricoeurs
        concept van de productieve verbeelding en de waarde daarvan voor het debat over de cognitieve waarde van literaire fictie in een themanummer rond filosofie en literatuur van het tijdschrift&nbsp;
        %em> Metodo
        ! .
    %p
      Daarnaast was ik gasthoofdredacteur van een themanummer rond de cognitieve waarde van fictie voor het tijdschrift&nbsp;
      %a{ :href => "https://www.aestheticinvestigations.eu/index.php/journal/issue/view/8", :target => "_blank" }> Aesthetic Investigations
      ! .
    %p
      In het najaar van 2019 verscheen bovendien mijn boek&nbsp;
      %a{ :href => "http://letterwerk.be/publ/watdelezer.html", :target => "_blank" }>
        %em> Wat de lezer leert
      , waarin hetzelfde onderzoek centraal staat.
    %p
      Sinds 2017 ben ik ook bestuurslid bij het 
      %a{ :href => "http://nge.nl", :target => "_blank" } Nederlands Genootschap voor Esthetica 
      en sinds begin 2020 maak ik deel uit van de redactie van het&nbsp;
      %a{ :href => "https://www.aup.nl/nl/journal/algemeen-nederlands-tijdschrift-voor-wijsbegeerte", :target => "_blank" }> Algemeen Nederlands Tijdschrift voor Wijsbegeerte 
      ! .  


.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3
      Masterthesis
    %p
      Ook het onderzoek voor mijn 
      %a{ :target => "_blank", :href => "https:www.academia.edu/7798212/De_literaire_ervaring_een_esthetische_ervaring" } masterthesis 
      bevond zich in het domein van de literatuurfilosofie. Specifiek richte mijn masterthesis zich op de vraag of de literaire ervaring beschouwd kan worden als een esthetische ervaring. Een deel van mijn argumentatie werkte ik daarna verder uit in een 
      %a{ :target => "_blank", :href => "http://www.aestheticinvestigations.eu/index.php/journal/article/view/37" } Engelstalig artikel 
      dat in 2015 verscheen in het tijdschrift Aesthetic Investigations.


.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2 
    %h3
      Bachelorscriptie
    %p
      De focus van mijn
      %a{ :target => "_blank", :href => "https://www.academia.edu/7798211/De_geëconomiseerde_samenleving._Nussbaum_en_Achterhuis_in_confrontatie_met_de_Frankfurter_Schule" } bachelorscriptie 
      lag verder verwijderd van mijn huidige onderzoek. Op basis van de kritiek die Max Horkheimer en Theodor W. Adorno in de jaren 1940 formuleerden op de cultuurindustrie analyseerde ik twee recente kritieken op het neoliberalisme, namelijk Hans Achterhuis’ De utopie van de vrije markt en Martha Nussbaum’s Not for Profit en Creating Capabilities.


.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3
      Blog
    %p
      Naast mijn academisch werk schrijf ik ook regelmatig kleinere, toegankelijkere artikels voor andere doeleinden. De meeste van die teksten zijn ook terug te vinden op mijn&nbsp;
      %a{ :target => "_blank", :href => "http://leenverheyen.wordpress.com" }> blog
      ! .

app/views/pages/home.html.haml
.row
  .jumbotron.col-md-10.offset-md-1
    = image_tag "leen_parijs.jpg", { :alt => "Leen Verheyen draagt voor op de Parijsavond van deBuren", :width => "100%", :height => "auto" }
  
.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %p 
    Filosofie en literatuur zijn waarschijnlijk de woorden waarmee mijn werk het best valt samen te vatten. Na een opleiding drama aan het conservatorium van Gent werkte ik als theatermaker, –auteur en –docent. Ik schreef theaterteksten voor gezelschappen als Villanella, HETPALEIS en Luxemburg en regisseerde daarnaast ook eigen voorstellingen. Mijn theaterwerk had daarbij bijna altijd een belangrijke onderzoekende component. Veel van mijn teksten kwamen tot stand na een lange periode van research en vormden de artistieke weergave van mijn eigen worstelingen of fascinaties ten opzichte van bepaalde maatschappelijke of menselijke fenomenen.
    
    %p 
      Daarnaast begon ik aan een opleiding filosofie aan de Universiteit Antwerpen. Die opleiding mondde uiteindelijk uit in een doctoraatsonderzoek in de literatuurfilosofie. In het bijzonder onderzoek ik daarbij welke invloed literaire fictie kan uitoefenen op onze blik op en ons handelen in de wereld. Dit onderwerp staat ook centraal in mijn eerste filosofische boek, 
      %a{ :href => "http://letterwerk.be/publ/watdelezer.html", :target => "_blank" }
        %em
          Wat de lezer leert
      , dat in het najaar van 2019 verscheen bij Letterwerk.
  
    %p Op deze website vind je meer informatie over zowel mijn filosofisch onderzoek als mijn literair werk (proza/theater/film).
      
    
  

app/views/pages/literatuur.html.haml
.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3
      Theater
    %p
      Het grootste deel van mijn literair werk bestaat uit theaterteksten. De meeste van die teksten zijn gratis te downloaden op deze website.
    %p
      In 2008 schreef ik als bachelorproef voor mijn drama-opleiding de theatertekst <a target=_blank href='../documents/parkeerterreinenblues.pdf'><strong>Parkeerterreinenblues</strong></a>.<div class='vid'><div class="youtube" data-embed='WBJSRUoBVCk'><div class="play-button"></div></div></div> In deze theatertekst voor twee spelers gaat een vrouw de confrontatie aan met de man die een paar maanden eerder haar dochter heeft doodgereden.
    %p
      Een jaar later maakte ik als masterproef de voorstelling <a target=_blank href='../documents/human_interest.pdf'><strong>Human Interest</strong></a>. Voor deze voorstelling deed ik onderzoek naar school shootings en andere vormen van mass shootings. De tekst bestaat uit twee monologen die door elkaar lopen en schijnbaar met elkaar in dialoog gaan, doorkruist door muziek.<br>
    %p  
      Theatergezelschap Plankton Hotel maakte later op basis van deze tekst de voorstelling&nbsp;
      %a{ :target => "_blank", :href => "http://www.planktonhotel.be/blikschade.html" }>
        %strong Blikschade
        ! .
    %p
      In 2010 maakte ik samen met muzikanten Jan Evenepoel en Sim Van Thienen van&nbsp;
      %a{ :target => "_blank", :href => "http://vi.be/headfullofflames" }> Head Full of Flames
      de locatievoorstelling&nbsp; 
      %a{ :target => "_blank", :href => "../documents/autoroute_du_soleil.pdf" }>
        %strong autoroute du soleil
      ! . Ook deze voorstelling bestaat uit twee monologen die af en toe met elkaar interageren. Twee personages vertellen het verhaal van een man die na een vechtscheiding met zijn dochter naar het buitenland vertrekt.
    .vid
      .youtube{ :data => { :embed => "YYZbP7xZpG8" } } 
        .play-button
    %p
      Een jaar later werkte ik opnieuw samen met Jan Evenepoel en Sim Van Thienen voor de monoloog&nbsp;
      %a{ :target => "_blank", :href => "../documents/smallfilm.pdf" }>
        %strong Smallfilm
      ! . Voor deze tekst onderzocht ik het fenomeen van de zogenaamde altruïstische kindermoord. Een meisje richt haar videocamera op het raam van haar buurvrouw. En kijkt. Een waanzinnig universum openbaart zich.
    %p  
      Daarnaast schreef ik ook enkele theaterteksten voor een jong publiek. In 2009 schreef ik in het kader van het project HETPALEISdebutanten van 
      %a{ :target => "_blank", :href => "http://www.hetpaleis.be/" } HETPALEIS 
      twee teksten voor kinderen. 
      %a{ :target => "_blank", :href => "../documents/meestal_regende_het.pdf" }
        %strong Meestal regende het 
      is een tekst voor kinderen vanaf 8 jaar over een jongen die een hele wereld in karton creëert en een meisje dat probeert breed te worden. 
      %a{ :target => "_blank", :href => "../documents/sarie_mijn_vriend_kaspar_en_ik.pdf" }
        %strong Sarie, mijn vriend Kaspar en ik
      is een tekst voor kleuters over een ogenschijnlijk onschuldig logeerpartijtje dat uitdraait op een gevaarlijk spel.
    %p
      Voor het participatieproject &quot;Bij de buren&quot;, waarmee jeugdtheatergezelschap Luxemburg kinderen en hun gezinnen laat proeven van theater, bewerkte ik het prentenboek “Keepvogel. Het diepste gat” van Wouter van Reek tot een theatertekst.
    %p
      Samen met Nele Van den Broeck schreef ik voor kinderen vanaf 5 jaar ook de tekst 
      %a{ :target => "_blank", :href => "../documents/kwijt.pdf" }
        %strong Kwijt 
      waarin er allerlei absurde situaties ontstaan wanneer plots alle woorden kwijt blijken te zijn.
    %p
      Ook met Margot Vyverman werkte ik samen aan theaterteksten. In 2011 maakten we samen de radiotheatervoorstelling 
      %strong Benefiet voor een komende natuurramp
      waarin we grote benefietprogramma’s parodiëerden, inclusief een benefietlied met bijbehorende videoclip.
      .vid
        .youtube{ :data => { :embed => "lfILb47y_EQ" } } 
          .play-button
    %p    
      Een jaar later maakten we, geïnspireerd op de documentaire “How to Start Your Own Country”, de voorstelling&nbsp;
      %strong> Banitova
      ! .
    .vid
      .youtube{ :data => { :embed => "KoZ9kRt6SB0" } } 
        .play-button
    %p
      Mijn recentste tekst voor theater zijn enkele korte verhaaltjes voor kinderen die ik schreef in opdracht van 
      %a{ :target => "_blank", :href => "http://www.huisbinnenweg.be" } Huis Binnenweg 
      voor hun muziek- en vertelvoorstelling Verteller en vriendinnetjes grote verhalenfestival. Deze voorstelling is komend seizoen op tournee. 
    
.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3 Proza
    %p
      Naast theaterteksten schrijf ik ook proza. Met mijn kortverhaal Sebastiaan was ik laureaat van WriteNow! Gent in 2009. Het verhaal werd daarna ook gepubliceerd in de bloemlezing Print is Dead. Nieuwe schrijvers uit Vlaanderen, uitgegeven bij Meulenhoff/Manteau. In 2013 belande mijn kortverhaal 
      %strong U 
      op de longlist van de Lowlands schrijfwedstrijd en werd het verhaal gepubliceerd in het gratis ebook De grote Lowlands schrijfwedstrijd 2013.&nbsp;
      %a{ :target => "_blank", :href => "https://www.goodreads.com/reader/50379-de-grote-lowlands-schrijfwedstrijd-2013-de-twintig-beste-inzendingen" }> De twintig beste inzendingen
      , uitgegeven door Nijgh & Van Ditmar. De tekst verscheen later ook op de website van het cultureel webtijdschrijft&nbsp;
      %a{ :target => "_blank", :href => "http://www.barbarus.org/#!U-/cu6k/56150de10cf25fa7fe2bdefd" }> Barbarus
      ! .
    %p
      In de zomer van 2013 mocht ik op uitnodiging van 
      %a{ :target => "_blank", :href => "http://www.deburen.eu" } deBuren
      twee weken op schrijfresidentie in Parijs. Daar schreef ik twee teksten, het kortverhaal 
      %a{ :target => "_blank", :href => "http://www.deburen.eu/nl/nieuws-opinie/detail/de-stad-die-ophield-en-verdween" } 
        %strong De stad die ophield en verdween
      en een&nbsp;
      %a{ :target => "_blank", :href => "http://www.deburen.eu/nl/nieuws-opinie/detail/poezie-bij-het-memorial-de-la-shoah" }> gedichtencyclus
      ! .
    %p
      In 2014 publiceerde ik online de “novelle in feuilletonvorm”&nbsp;
      %strong> Kleine Opstand
      ! . Elke week verscheen een nieuw hoofdstuk van het verhaal online. Het – inmiddels volledige – verhaal is 
      %a{ :target => "_blank", :href => "https://kleineopstand.wordpress.com/about/" } hier
      te lezen.

.row    
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3 Poëzie
    %p
      Op dit moment werk ik in de eerste plaats aan poëzie. Hier en daar verschijnen er losse gedichten van mij in druk en daarnaast sta ik ook regelmatig met eigen werk op het podium. Online kan je werk van mij vinden op bijvoorbeeld de websites 
      %a{ :href => "http://www.hetgezeefdegedicht.be/2019-04.php", :target => "_blank" } Het gezeefde gedicht
      of&nbsp;
      %a{ :href => "http://azertyfactor.be/profiel-van-leen-verheyen/1733", :target => "_blank" }> Azertyfactor
      ! . 
    .vid
      .youtube{ :data => { :embed => "9dxEC-hSBtg" } }
        .play-button
                

.row
  %article.note.col-xs-12.col-md-10.offset-md-1.col-lg-8.offset-lg-2
    %h3 Film
    %p
      Naast theater en proza werk ik ook occasioneel mee aan filmprojecten. Zo schreef ik samen met Jeroen Sebrechts het scenario voor de kortfilm&nbsp;
      %strong> Free Flow
      ! .
    .vid
      %div{ :style => "padding:56.25% 0 0 0;position:relative;" }
        %iframe.vimeo{ :data => { :src => "https://player.vimeo.com/video/68393693" }, :src => "", :style => "position:absolute;top:0;left:0;width:100%;height:100%;", :frameborder => "0", :webkitallowfullscreen => true, :mozallowfullscreen => true, :allowfullscreen => true }
      %script{ :src => "https://player.vimeo.com/api/player.js" } 
    %p
      Deze Hongaars-Belgisch-Finse coproductie werd geselecteerd voor verschillende filmfestivals en won in 2016 het Long Take Florence Film Festival.
 
.col-lg-6.hidden-xs.hidden-sm.hidden-md
  .tackWrapper.extraLeen
    = image_tag "leen.jpg", { :alt => "Leen Verheyen", :width => "100%", :height => "auto" }

app/views/shared/_flash_messages.html.haml
- if obj.errors.any?
  %ul
  - obj.errors.full_messages.each do |msg|
    %li
      = msg

app/views/shared/_footer.html.haml
%footer.row
  .col-xs-12.col-lg-10.offset-lg-1	
    .row
      .col-md-4
        %a{ :href => "", :class => "email"}
        :javascript
          var mail = ["leen.verheyen", "@", "uantwerpen", ".be"].join("");
          var href = `mailto:${mail}`;
          var email = document.querySelector(".email");
          email.setAttribute("href", href);
          email.innerText = mail;
        %div
          %a{ :target => "_blank", :href => "https://twitter.com/VerheyenLeen" }
            = image_tag "twitter_logo.png", { :class => "twit"}
      .col-md-4
        %p
          Je vindt Leen ook op:
        %p
          %a{ :target => "_blank", :href => "http://uantwerpen.academia.edu/LeenVerheyen" } 
            Academia
        %p
          %a{ :target => "_blank", :href => "https://www.uantwerpen.be/nl/personeel/leen-verheyen/"} 
            Universiteit Antwerpen
        %p
          %a{ :target => "_blank", :href => "https://leenverheyen.wordpress.com" }
            Wordpress
      .col-md-4
        .copyright
          %span.copy-symbol
            &copy;
          = "#{Time.new.year.to_s} Leen Verheyen" 
        #website_by
          webdesign: Augustin Grenné

app/views/shared/_header.html.haml
%header
  - if current_user
    %aside.admin
      = link_to "log out", logout_path

  -# mobile menu
  %nav.d-md-none
    .row.d-flex.justify-content-center
      .hamburger.note{ :onclick => "toggleMenu()" } 
        .hamburger-open
          %div
            &mdash;
          %div
            &mdash;
          %div
            &mdash;
    .nav-mobile.d-flex.flex-column.justify-content-around{ :hidden => true }
      .d-flex.justify-content-center.hamburger-close{ :onclick => "toggleMenu()" }
        %span
          X
      .d-flex.justify-content-center
        = link_to "leen", root_path()
      .d-flex.justify-content-center
        = link_to "filosofie", filosofie_path()
      .d-flex.justify-content-center
        = link_to "literatuur", literatuur_path()
      .d-flex.justify-content-center
        = link_to "nieuws", news_items_path()
      .d-flex.justify-content-center
        = image_tag "logo.png", { :alt => "logo Leen Verheyen", :height => "75" }
    
  -# menu for medium screens and above
  %nav.row
    .col-lg-10.offset-lg-1.d-none.d-md-flex.justify-content-around.align-items-center
      .note
        - img = image_tag "logo.png", { :alt => "logo Leen Verheyen", :height => "150" }
        = link_to img, root_path(), { :class => "logo" }
      .note
        = link_to "filosofie", filosofie_path()
      .note
        = link_to "literatuur", literatuur_path()
      .note
        = link_to "nieuws", news_items_path()

  :javascript 
    function toggleMenu() {
      document.querySelector(".nav-mobile").toggleAttribute("hidden");
      if (!document.querySelector(".nav-mobile").hasAttribute("hidden")){
        document.querySelector("body").style.overflow = "hidden";
      }
      else{
        document.querySelector("body").style.overflow = "initial";
      }
    }